/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mySidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'intro',
    },
    {
      type: 'link',
      label: 'Tutorial',
      href: 'https://nextjournal.com/dubroy/ohm-parsing-made-easy',
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'doc',
          label: 'Syntax reference',
          id: 'syntax-reference',
        },
        {
          type: 'doc',
          label: 'API reference',
          id: 'api-reference',
        },
        {
          type: 'doc',
          label: 'Extras',
          id: 'extras',
        },
        {
          type: 'doc',
          label: 'Errors',
          id: 'errors',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'doc',
          label: 'Using with TypeScript',
          id: 'typescript',
        },
        {
          type: 'doc',
          label: 'Publishing grammars',
          id: 'publishing-grammars',
        },
        {
          type: 'doc',
          label: 'Contributing',
          id: 'contributor-guide',
        },
        {
          type: 'doc',
          label: 'Philosophy',
          id: 'philosophy',
        },
        {
          type: 'doc',
          label: 'Docker',
          id: 'docker',
        },
      ],
    },
    {
      type: 'category',
      label: 'Release notes',
      items: [
        {
          type: 'doc',
          label: 'v18.0 Beta',
          id: 'releases/ohm-js-18.0',
        },
        {
          type: 'category',
          label: 'v17.0 (Latest)',
          link: {
            type: 'doc',
            id: 'releases/ohm-js-17.0',
          },
          items: [
            {
              type: 'doc',
              label: 'Indentation-sensitive languages',
              id: 'indentation-sensitive',
            },
            {
              type: 'doc',
              label: 'Incremental semantics',
              id: 'incremental-semantics',
            },
          ],
        },
        {
          type: 'doc',
          label: 'v16.0',
          id: 'releases/ohm-js-16.0',
        },
        {
          type: 'doc',
          label: 'Miniohm',
          id: 'design/miniohm',
        },
      ],
    },
    {
      type: 'doc',
      label: 'Patterns and pitfalls',
      id: 'patterns-and-pitfalls',
    },
  ],
};

module.exports = sidebars;
